### ISSUE TITLE
Export/Import of template includes BB code setting but adds HTML line breaks.

### ISSUE THREAD

**Issue by kevrwill** [beaverbuilder/bb-code-settings#11]
I saved a template with Posts modules - there are BB code settings with CSS included. I've exported this template and imported it elsewhere. The imported template includes the line breaks, breaking the CSS. 
![image](https://user-images.githubusercontent.com/57111570/221965142-b86f1a8f-dd93-4849-90e4-40fb5d6c1fc5.png)
![image (3)](https://user-images.githubusercontent.com/57111570/221965233-94e0b3c4-01a9-498d-ba9d-d36228084625.png)

**Comment by Pross** [comment]
Thanks for reporting this we are tracking it in 2.7 branch where a version of this code has been merged into the main plugin.
Keep an eye on changelogs for a fix.
