### ISSUE TITLE
Using BB 2.3, adding CSS gave me a fatal error

### ISSUE THREAD

**Issue by taricco** [beaverbuilder/bb-code-settings#2]
For the Title module, I added some simple CSS and the template would not save and hence gave me a fatal error.

**Comment by fastlinemedia** [comment]
Hi @taricco, thanks for the report. Do you mean the heading module or post title module in Themer? 

Can you send along the CSS you added? 

Thanks!

**Comment by fastlinemedia** [comment]
@taricco we've identified the issue and fixed it in the latest master branch. Let me know if you run into anything else.
