### ISSUE TITLE
Critical error when in the page builder UI if using MooSend forms

### ISSUE THREAD

**Issue by DavidWaumsley** [beaverbuilder/bb-code-settings#4]
Hello, 
I can't find a way to use both bb code setting and MooSend. I get a critical error when entering the page builder. Below is the script they use. The same happens with their WP plugin although the issue is confined to the page their shortcode is on.

<script>
//load TrackerJS
!function(t,n,e,o,a){function d(t){var n=~~(Date.now()/3e5),o=document.createElement(e);o.async=!0,o.src=t+"?ts="+n;var a=document.getElementsByTagName(e)[0];a.parentNode.insertBefore(o,a)}t.MooTrackerObject=a,t[a]=t[a]||function(){return t[a].q?void t[a].q.push(arguments):void(t[a].q=[arguments])},window.attachEvent?window.attachEvent("onload",d.bind(this,o)):window.addEventListener("load",d.bind(this,o),!1)}(window,document,"script","//cdn.stat-track.com/statics/moosend-tracking.min.js","mootrack");
//tracker has to be initialized otherwise it will generate warnings and wont sendtracking events
mootrack('init', '9d4e545091e34fcfaa2311610ad725f5');
</script>

This shows the form: <div data-mooform-id="42ceb22e-fe21-481d-a1f9-f3fba55ed929" ></div>

Thank you

**Comment by fastlinemedia** [comment]
Hey @DavidWaumsley, thanks for posting. To recreate this, all I need is that script on the page and to open the builder? How are you getting that script on the page?

**Comment by DavidWaumsley** [comment]
@fastlinemedia  So sorry I had a computer fail and missed your response here. Thank you,

Oddly the update you recently did (adding safe mode) appears to have solved my issue too (although there have been both BB and WP updates since).

If the problem returns I will send you a login to the install.

Thanks again
