### ISSUE TITLE
critical error when mistaken syntax in css

### ISSUE THREAD

**Issue by danj-O** [beaverbuilder/bb-code-settings#5]
I was going along my merry old way adding some custom js and css to my bb with code settings and accudentally put a colon instead of a semi-colon somewhere and I got a critical error and can't get back into the editor to fix it! what do I do? Are you aware of this issue?

**Comment by fastlinemedia** [comment]
Hey @danj-O, thanks for posting and sorry to hear about the issue. 

Can you try BB's safe mode to see if that'll let you get in there and remove the bad code? 

https://docs.wpbeaverbuilder.com/beaver-builder/troubleshooting/debugging/safe-mode/

Let me know how it goes.

Justin

**Comment by codente** [comment]
@fastlinemedia I recommended safe mode to him in the forum.  Said it didn't work

https://community.wpbeaverbuilder.com/t/simple-css-error-locking-me-out-of-bb/12796/5

**Comment by danj-O** [comment]
As codente said, I tried safe mode and the page still wouldn't load to make edits. So strange, all it was was a colon instead of a semi-colon.  In the end, I really needed to continue working, so I got rid of this plugin and I've been using the cmd+y input area for css and js.  The weird part is that if I try to load code-settings back up after deleting and reinstalling, I immediately crash again.

**Comment by fastlinemedia** [comment]
Thanks for the info. I'll see about making this plugin compatible with safe mode in case this comes up again.

**Comment by danj-O** [comment]
cool beans! I'll give the plugin a try again once this is fixed.  Kinda hard to use if I can't ever make any mistakes.  Otherwise, love the convenience of this plugin! Thanks for your efforts!

**Comment by fastlinemedia** [comment]
Hey @danj-O, the fix is merged. Install a new copy and let us know how it goes :)
