### ISSUE TITLE
Incompatibility with wp-scss plugin

### ISSUE THREAD

**Issue by Twanneman** [beaverbuilder/bb-code-settings#9]
Hi Justin, 

1) I recently activated this plugin on my own site and it broke my setup because I was already using the wp-scss plugin. Is there any way to make them work together?

2) Would it possible to write SCSS in the bb code settings? I think it currently only supports regular css? 
 
Kind regards, Twan

**Comment by fastlinemedia** [comment]
Hey @Twanneman, thanks for bringing this to our attention. I just pushed an update to this repo that should fix the fatal error. Regarding point 2, you should be able to use SCSS within the fields this plugin adds. Let me know if you run into any issues with that.
